when:
  - event: [deployment]

labels:
  platform: linux/amd64
  backend: local
  node: production

steps:
  - name: deploy
    image: bash
    environment:
      CI_PIPELINE_DEPLOY_TARGET: production
      SCRIPT:
        from_secret: deploy_wci_script
      REGISTRY_USER:
        from_secret: docker_username
      REGISTRY_PASS:
        from_secret: docker_password
      REGISTRY_BASE_PATH_ENV:
        from_secret: secret_registry_base_path
    commands:
      - echo $${REGISTRY_PASS} | docker login -u $${REGISTRY_USER} --password-stdin $${REGISTRY_BASE_PATH_ENV}
      - sh $${SCRIPT}
